# Generated by Django 3.2.13 on 2022-06-08 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0003_auto_20220607_0754"),
        ("mainapp", "0004_coursefeedback"),
    ]

    operations = []
